### ISSUE TITLE
Update API Response Model

### ISSUE THREAD

**Issue by richardleach** [davorg/net-songkick#2]
From working on #1, it looks like the response model needs updating to reflect some new attributes on a few objects, the missing City object, and arrays of MusicBrainz identifiers.

I've made a start on this first before going back to #1.

**Comment by davorg** [comment]
Sounds great. Thanks for taking it on.

**Comment by richardleach** [comment]
Progress to date is over at [this fork commit](https://github.com/richardleach/net-songkick/commit/8163c649fa307162e7aea681fa72312cbed91356)
